name: test_project
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  cupertino_icons: 1.0.2
  dio: 4.0.6
  equatable: 2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: 8.0.1
  json_annotation: 4.5.0
  json_serializable: 6.2.0
  localstorage: 4.0.0+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.1.11
flutter:
  uses-material-design: true
  assets:
    - assets/
